apiVersion: v1
kind: Pod
metadata:
  name: annotation-default-scheduler
  labels:
    name: multischeduler-example
  
spec:
  schedulerName: herodotus-scheduler
  containers:
  - name: test-pod
    image: registry.k8s.io/pause:2.0