name: Docker Image CI

on:
  push:
    branches: [ herodotus ]
  pull_request:
    branches: [ herodotus ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build scheduler
      run: . build/run.sh make kube-scheduler  
      working-directory: ./kubernetes_src
    - name: Login to container registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build Docker image
      run: | 
        docker build . --file Dockerfile --tag ghcr.io/dsmaugy/kubernetes-herodotus/herodotus-scheduler:latest
    - name: Push Docker image
      run: docker push ghcr.io/dsmaugy/kubernetes-herodotus/herodotus-scheduler:latest